name: Basic Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  _R_CHECK_FORCE_SUGGESTS_: false

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        R: ["4.4.3"]

    steps:
      - name: Loop for an hour
        run: |
          for i in {1..60}
          do 
          echo $i
          curl --max-time 120 'https://biobank.ndph.ox.ac.uk/showcase/scdown.cgi?fmt=txt&id=7'
          sleep 60
          done
